name: Reproducibility
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install reproducibleRchunks
        run: R -e "install.packages('reproducibleRchunks')"
      - name: Run reproducibility checks
        run: |
          Rscript - <<'EOF'
          library(reproducibleRchunks)
          files <- list.files(pattern = '\\.[Rr]md$', recursive = TRUE)
          success <- all(sapply(files, isReproducible))
          if (success) {
            download.file('https://img.shields.io/badge/reproduced-brightgreen.svg', 'reproduced.svg', mode = 'wb')
          } else {
            download.file('https://img.shields.io/badge/reproduced-failing-red.svg', 'reproduced.svg', mode = 'wb')
            quit(status = 1)
          }
          EOF
      - uses: actions/upload-artifact@v4
        with:
          name: reproduced-badge
          path: reproduced.svg
