name: Reproducibility
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install package
        run: R CMD INSTALL .
      - name: Run reproducibility checks
        run: |
          Rscript - <<'EOF'
          files <- list.files(pattern = '\.[Rr]md$', recursive = TRUE)
          success <- all(sapply(files, reproducibleRchunks::isReproducible))
          if (success) {
            download.file('https://img.shields.io/badge/reproduced-brightgreen.svg', 'reproduced.svg', mode = 'wb')
          } else {
            download.file('https://img.shields.io/badge/reproduced-failing-red.svg', 'reproduced.svg', mode = 'wb')
            quit(status = 1)
          }
          EOF
      - uses: actions/upload-artifact@v3
        with:
          name: reproduced-badge
          path: reproduced.svg
